//
//  BusinessModel.swift
//  PathPrize
//
//  Created by nagesh sairam on 4/25/24.
//

import Foundation

struct Business: Codable {
    let id: Int?          // Using Optional because the ID is generated by the database upon creation
    let createdAt: Date     // Timestamp with time zone
    let userId: UUID?       // This can be nil, hence Optional
    let name: String?       // Optional string
    let address: String?    // Optional string
    let zip: Int64?         // Optional bigint

    enum CodingKeys: String, CodingKey {
        case id
        case createdAt = "created_at"
        case userId = "user_id"
        case name
        case address
        case zip
    }
}
