//
//  BusinessModel.swift
//  PathPrize
//
//  Created by nagesh sairam on 4/25/24.
//

import Foundation

struct Business: Codable {
    let id: UUID?          // Using Optional because the ID is generated by the database upon creation
    let userId: UUID?       // This can be nil, hence Optional
    let name: String?       // Optional string
    let address: String?    // Optional string
    let avatar_url: String?
    let email: String?
    let onboardingState: String?

    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case name
        case address
        case avatar_url
        case email
        case onboardingState = "onboarding_state"
    }
}


