//
//  RewardModel.swift
//  PathPrize
//
//  Created by nagesh sairam on 4/25/24.
//

import Foundation

struct RewardModel: Codable, Identifiable {
    let id: Int?               // Optional because it's auto-generated by the database
    let createdAt: Date          // Date and time the reward was created, timestamp with timezone
    let userId: UUID?            // Optional UUID, can be null if not linked to a user
    let activityId: Int64?       // Optional ID linking to an activity
    let rewardObjectUrl: String? // Optional URL as a string
    let status: String?          // Optional status of the reward
    let offerId: Int64?          // Optional ID linking to an offer
    let qrCode: UUID
    let name: String
    let expiresAt: Date

    enum CodingKeys: String, CodingKey {
        case id
        case createdAt = "created_at"
        case userId = "user_id"
        case activityId = "activity_id"
        case rewardObjectUrl = "reward_object_url"
        case status
        case offerId = "offer_id"
        case qrCode =  "qr_code"
        case name
        case expiresAt = "expires_at"
    }
}
